export const REGISTER_SUCCESSFULLY = 'REGISTER_SUCCESSFULLY';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const CLEAN_ALERT = 'CLEAN_ALERT';

export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';

