export const REGISTER_SUCCESSFULLY = 'REGISTER_SUCCESSFULLY';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGIN_SUCCESSFULLY = 'LOGIN_SUCCESSFULLY';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';
export const SIGN_OFF = 'SIGN_OFF';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR';

export const CREATE_LINK_SUCCESS = 'CREATE_LINK_SUCCESS';
export const CREATE_LINK_ERROR = 'CREATE_LINK_ERROR';
